### ISSUE TITLE
Bug in the Course Service to join course event and user events

### ISSUE THREAD

**Issue by MrMoon** [Apollo-LW/course#7]
I am unable to join the events from the course topic with the events in the user topics to provide the courses that the user is enrolled in, yet.

**Comment by MrMoon** [comment]
Idea: 
1. Create CourseEvent to handle the members of each course
2. Create a UserCourse to handle user courses
3. Stream CourseEvents, group them by memberId
4. Reduce with oldUserCourse, newUserCourse to newUserCourse.add(oldUserCourse.members)

**Comment by MrMoon** [comment]
Found the Bug :) 
`Deserialization exception handler is set to fail upon a deserialization error. If you would rather have the streaming pipeline continue after a deserialization error, please set the default.deserialization.exception.handler appropriately.
	at org.apache.kafka.streams.processor.internals.RecordDeserializer.deserialize(RecordDeserializer.java:80)
	at org.apache.kafka.streams.processor.internals.RecordQueue.updateHead(RecordQueue.java:176)
	at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:112)
	at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:185)
	at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:865)
	at org.apache.kafka.streams.processor.internals.TaskManager.addRecordsToTasks(TaskManager.java:938)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:640)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:551)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:510)
Caused by: java.lang.IllegalArgumentException: The class 'com.apollo.course.model.Course' is not in the trusted packages: [java.util, java.lang]. If you believe this class is safe to deserialize, please provide its name. If the serialization is only done by a trusted source, you can also enable trust all (*).
	at org.springframework.kafka.support.converter.DefaultJackson2JavaTypeMapper.getClassIdType(DefaultJackson2JavaTypeMapper.java:126)
	at org.springframework.kafka.support.converter.DefaultJackson2JavaTypeMapper.toJavaType(DefaultJackson2JavaTypeMapper.java:100)
	at org.springframework.kafka.support.serializer.JsonDeserializer.deserialize(JsonDeserializer.java:504)
	at org.apache.kafka.streams.processor.internals.SourceNode.deserializeValue(SourceNode.java:55)
	at org.apache.kafka.streams.processor.internals.RecordDeserializer.deserialize(RecordDeserializer.java:66)
	... 8 more`

**Comment by MrMoon** [comment]
Solved but found another bug
`ERROR 6816 --- [-StreamThread-1] o.a.k.s.e.LogAndFailExceptionHandler     : Exception caught during Deserialization, taskId: 1_0, topic: apollo-course-course-user-state-store-repartition, partition: 0, offset: 0

java.lang.IllegalArgumentException: The class 'com.apollo.course.model.Course' is not in the trusted packages: [java.util, java.lang]. If you believe this class is safe to deserialize, please provide its name. If the serialization is only done by a trusted source, you can also enable trust all (*).
	at org.springframework.kafka.support.converter.DefaultJackson2JavaTypeMapper.getClassIdType(DefaultJackson2JavaTypeMapper.java:126) ~[spring-kafka-2.6.3.jar:2.6.3]
	at org.springframework.kafka.support.converter.DefaultJackson2JavaTypeMapper.toJavaType(DefaultJackson2JavaTypeMapper.java:100) ~[spring-kafka-2.6.3.jar:2.6.3]
	at org.springframework.kafka.support.serializer.JsonDeserializer.deserialize(JsonDeserializer.java:504) ~[spring-kafka-2.6.3.jar:2.6.3]
	at org.apache.kafka.streams.processor.internals.SourceNode.deserializeValue(SourceNode.java:55) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.RecordDeserializer.deserialize(RecordDeserializer.java:66) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.RecordQueue.updateHead(RecordQueue.java:176) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:112) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:185) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:865) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.TaskManager.addRecordsToTasks(TaskManager.java:938) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:640) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:551) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:510) ~[kafka-streams-2.6.0.jar:na]`

**Comment by MrMoon** [comment]
Solved, found another bug
`
ERROR 6816 --- [-StreamThread-1] o.a.k.s.e.LogAndFailExceptionHandler     : Exception caught during Deserialization, taskId: 1_0, topic: apollo-course-course-user-state-store-repartition, partition: 0, offset: 0

java.lang.IllegalArgumentException: The class 'com.apollo.course.model.Course' is not in the trusted packages: [java.util, java.lang]. If you believe this class is safe to deserialize, please provide its name. If the serialization is only done by a trusted source, you can also enable trust all (*).
	at org.springframework.kafka.support.converter.DefaultJackson2JavaTypeMapper.getClassIdType(DefaultJackson2JavaTypeMapper.java:126) ~[spring-kafka-2.6.3.jar:2.6.3]
	at org.springframework.kafka.support.converter.DefaultJackson2JavaTypeMapper.toJavaType(DefaultJackson2JavaTypeMapper.java:100) ~[spring-kafka-2.6.3.jar:2.6.3]
	at org.springframework.kafka.support.serializer.JsonDeserializer.deserialize(JsonDeserializer.java:504) ~[spring-kafka-2.6.3.jar:2.6.3]
	at org.apache.kafka.streams.processor.internals.SourceNode.deserializeValue(SourceNode.java:55) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.RecordDeserializer.deserialize(RecordDeserializer.java:66) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.RecordQueue.updateHead(RecordQueue.java:176) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.RecordQueue.addRawRecords(RecordQueue.java:112) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.PartitionGroup.addRawRecords(PartitionGroup.java:185) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamTask.addRecords(StreamTask.java:865) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.TaskManager.addRecordsToTasks(TaskManager.java:938) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:640) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:551) ~[kafka-streams-2.6.0.jar:na]
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:510) ~[kafka-streams-2.6.0.jar:na]
`

**Comment by MrMoon** [comment]
Found the bug, there was an extra tab in the yml file, so the function of the processor was not binded

[https://pbs.twimg.com/media/EjuK8ZhVoAAi4D6.png]

but there is a warn now for the consumers
`2020-12-24 13:18:58.809  WARN 13935 --- [-StreamThread-1] org.apache.kafka.clients.NetworkClient   : [Consumer clientId=apollo-course-d17b1048-2f4c-49c8-99d0-c7c65ed4fcd8-StreamThread-1-consumer, groupId=apollo-course] Error while fetching metadata with correlation id 11 : {apollo-course-KSTREAM-AGGREGATE-STATE-STORE-0000000002-repartition=UNKNOWN_TOPIC_OR_PARTITION}
2020`

**Comment by MrMoon** [comment]
oh god I found another extra space [https://i.imgflip.com/aw6ug.jpg]

**Comment by MrMoon** [comment]
Solved the warning 
now it's a deserialization issue
`Exception caught in process. taskId=0_0, processor=KSTREAM-SOURCE-0000000000, topic=course, partition=0, offset=0, stacktrace=java.lang.IllegalStateException: No headers available and no default type provided`

**Comment by MrMoon** [comment]
custom Serdes FTW [https://media.giphy.com/media/l3q2Z6S6n38zjPswo/giphy.gif]
